#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: meson
#
Name     : libgedit-amtk
Version  : 5.8.0
Release  : 1
URL      : https://gedit-technology.net/tarballs/libgedit-amtk/libgedit-amtk-5.8.0.tar.xz
Source0  : https://gedit-technology.net/tarballs/libgedit-amtk/libgedit-amtk-5.8.0.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-3.0
Requires: libgedit-amtk-data = %{version}-%{release}
Requires: libgedit-amtk-lib = %{version}-%{release}
Requires: libgedit-amtk-license = %{version}-%{release}
Requires: libgedit-amtk-locales = %{version}-%{release}
BuildRequires : buildreq-meson
BuildRequires : docbook-xml
BuildRequires : glib-dev
BuildRequires : gtk-doc
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(gobject-introspection-1.0)
BuildRequires : pkgconfig(gtk+-3.0)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
libgedit-amtk - Actions, Menus and Toolbars Kit for GTK applications
====================================================================

%package data
Summary: data components for the libgedit-amtk package.
Group: Data

%description data
data components for the libgedit-amtk package.


%package dev
Summary: dev components for the libgedit-amtk package.
Group: Development
Requires: libgedit-amtk-lib = %{version}-%{release}
Requires: libgedit-amtk-data = %{version}-%{release}
Provides: libgedit-amtk-devel = %{version}-%{release}
Requires: libgedit-amtk = %{version}-%{release}

%description dev
dev components for the libgedit-amtk package.


%package doc
Summary: doc components for the libgedit-amtk package.
Group: Documentation

%description doc
doc components for the libgedit-amtk package.


%package lib
Summary: lib components for the libgedit-amtk package.
Group: Libraries
Requires: libgedit-amtk-data = %{version}-%{release}
Requires: libgedit-amtk-license = %{version}-%{release}

%description lib
lib components for the libgedit-amtk package.


%package license
Summary: license components for the libgedit-amtk package.
Group: Default

%description license
license components for the libgedit-amtk package.


%package locales
Summary: locales components for the libgedit-amtk package.
Group: Default

%description locales
locales components for the libgedit-amtk package.


%prep
%setup -q -n libgedit-amtk-5.8.0
cd %{_builddir}/libgedit-amtk-5.8.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1695736594
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
meson test -C builddir --print-errorlogs

%install
mkdir -p %{buildroot}/usr/share/package-licenses/libgedit-amtk
cp %{_builddir}/libgedit-amtk-%{version}/LICENSES/LGPL-3.0-or-later.txt %{buildroot}/usr/share/package-licenses/libgedit-amtk/757b86330df80f81143d5916b3e92b4bcb1b1890 || :
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang libgedit-amtk-5

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/Amtk-5.typelib
/usr/share/gir-1.0/*.gir

%files dev
%defattr(-,root,root,-)
/usr/include/libgedit-amtk-5/amtk/amtk-action-info-central-store.h
/usr/include/libgedit-amtk-5/amtk/amtk-action-info-store.h
/usr/include/libgedit-amtk-5/amtk/amtk-action-info.h
/usr/include/libgedit-amtk-5/amtk/amtk-action-map.h
/usr/include/libgedit-amtk-5/amtk/amtk-application-window.h
/usr/include/libgedit-amtk-5/amtk/amtk-enum-types.h
/usr/include/libgedit-amtk-5/amtk/amtk-factory.h
/usr/include/libgedit-amtk-5/amtk/amtk-gmenu.h
/usr/include/libgedit-amtk-5/amtk/amtk-init.h
/usr/include/libgedit-amtk-5/amtk/amtk-menu-item.h
/usr/include/libgedit-amtk-5/amtk/amtk-menu-shell.h
/usr/include/libgedit-amtk-5/amtk/amtk-shortcuts.h
/usr/include/libgedit-amtk-5/amtk/amtk-utils.h
/usr/include/libgedit-amtk-5/amtk/amtk.h
/usr/lib64/libgedit-amtk-5.so
/usr/lib64/pkgconfig/libgedit-amtk-5.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/gtk-doc/html/libgedit-amtk-5/AmtkActionInfo.html
/usr/share/gtk-doc/html/libgedit-amtk-5/AmtkActionInfoCentralStore.html
/usr/share/gtk-doc/html/libgedit-amtk-5/AmtkActionInfoStore.html
/usr/share/gtk-doc/html/libgedit-amtk-5/AmtkApplicationWindow.html
/usr/share/gtk-doc/html/libgedit-amtk-5/AmtkFactory.html
/usr/share/gtk-doc/html/libgedit-amtk-5/AmtkMenuShell.html
/usr/share/gtk-doc/html/libgedit-amtk-5/annexes.html
/usr/share/gtk-doc/html/libgedit-amtk-5/annotation-glossary.html
/usr/share/gtk-doc/html/libgedit-amtk-5/api-index-2-0.html
/usr/share/gtk-doc/html/libgedit-amtk-5/api-index-3-0.html
/usr/share/gtk-doc/html/libgedit-amtk-5/api-index-4-0.html
/usr/share/gtk-doc/html/libgedit-amtk-5/api-index-5-0.html
/usr/share/gtk-doc/html/libgedit-amtk-5/api-index-5-6.html
/usr/share/gtk-doc/html/libgedit-amtk-5/api-index-full.html
/usr/share/gtk-doc/html/libgedit-amtk-5/api-reference.html
/usr/share/gtk-doc/html/libgedit-amtk-5/gradual-porting.html
/usr/share/gtk-doc/html/libgedit-amtk-5/home.png
/usr/share/gtk-doc/html/libgedit-amtk-5/index.html
/usr/share/gtk-doc/html/libgedit-amtk-5/left-insensitive.png
/usr/share/gtk-doc/html/libgedit-amtk-5/left.png
/usr/share/gtk-doc/html/libgedit-amtk-5/libgedit-amtk-5-Amtk-Initialization-and-Finalization.html
/usr/share/gtk-doc/html/libgedit-amtk-5/libgedit-amtk-5-AmtkActionMap.html
/usr/share/gtk-doc/html/libgedit-amtk-5/libgedit-amtk-5-AmtkGmenu.html
/usr/share/gtk-doc/html/libgedit-amtk-5/libgedit-amtk-5-AmtkMenuItem.html
/usr/share/gtk-doc/html/libgedit-amtk-5/libgedit-amtk-5-AmtkShortcuts.html
/usr/share/gtk-doc/html/libgedit-amtk-5/libgedit-amtk-5-AmtkUtils.html
/usr/share/gtk-doc/html/libgedit-amtk-5/libgedit-amtk-5.devhelp2
/usr/share/gtk-doc/html/libgedit-amtk-5/libgedit-amtk-intro.html
/usr/share/gtk-doc/html/libgedit-amtk-5/object-tree.html
/usr/share/gtk-doc/html/libgedit-amtk-5/right-insensitive.png
/usr/share/gtk-doc/html/libgedit-amtk-5/right.png
/usr/share/gtk-doc/html/libgedit-amtk-5/style.css
/usr/share/gtk-doc/html/libgedit-amtk-5/up-insensitive.png
/usr/share/gtk-doc/html/libgedit-amtk-5/up.png

%files lib
%defattr(-,root,root,-)
/usr/lib64/libgedit-amtk-5.so.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libgedit-amtk/757b86330df80f81143d5916b3e92b4bcb1b1890

%files locales -f libgedit-amtk-5.lang
%defattr(-,root,root,-)

